#!/bin/bash
# Builds the engine bridge for iPad and the simulator and packs it as an XCFramework.
# Usage: build-xcframework.sh [--cpu <llvm-cpu>]   (e.g. --cpu apple-m1)
set -euo pipefail
export PATH="/opt/homebrew/opt/rustup/bin:$PATH"
export IPHONEOS_DEPLOYMENT_TARGET=26.0
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CPU=""
[[ "${1:-}" == "--cpu" ]] && CPU="${2:?usage: --cpu <name>}"
FLAGS=""
[[ -n "$CPU" ]] && FLAGS="-C target-cpu=$CPU"
export RUSTFLAGS="$FLAGS"

cd "$ROOT/Engine"
for T in aarch64-apple-ios aarch64-apple-ios-sim; do
    cargo build -p unveil-ffi --release --target "$T"
done

# Link flags come from rustc itself, so they follow the engine's real native deps.
LIBS=$(cargo rustc -p unveil-ffi --release --target aarch64-apple-ios \
    --crate-type staticlib -- --print native-static-libs 2>&1 | sed -n 's/.*native-static-libs: //p' | tail -1)
[[ -n "$LIBS" ]] || { echo "no native-static-libs line from rustc" >&2; exit 1; }
mkdir -p "$ROOT/Config"
printf '// Generated by scripts/build-xcframework.sh. Do not edit.\nOTHER_LDFLAGS = $(inherited) %s\n' "$LIBS" \
    > "$ROOT/Config/UnveilEngine.xcconfig"

OUT="$ROOT/Frameworks/UnveilEngine.xcframework"
rm -rf "$OUT"
xcodebuild -create-xcframework \
    -library target/aarch64-apple-ios/release/libunveil_ffi.a     -headers ffi/include \
    -library target/aarch64-apple-ios-sim/release/libunveil_ffi.a -headers ffi/include \
    -output "$OUT"
echo "built $OUT${CPU:+ (target-cpu=$CPU)}"
